# /********************************************************************************
# * Copyright (c) 2022 Contributors to the Eclipse Foundation
# *
# * See the NOTICE file(s) distributed with this work for additional
# * information regarding copyright ownership.
# *
# * This program and the accompanying materials are made available under the
# * terms of the Apache License 2.0 which is available at
# * http://www.apache.org/licenses/LICENSE-2.0
# *
# * SPDX-License-Identifier: Apache-2.0
# ********************************************************************************/

name: dev-container-build

on:
  push:
    paths:
      - "tools/Dockerfile"
    branches:
      - main
  workflow_dispatch:
    inputs:
      tag:
        description: "tag of the docker container, eg:latest, v0.2.1"
        required: false
        default: "latest"
  workflow_call:
    inputs:
      tag:
        description: "tag of the docker container, eg:latest, v0.2.1"
        type: string
        required: false
        default: "latest"

jobs:

  get_tag:
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.eval_tag.outputs.tag }}
    steps:
      - name: Get tag from workflow / workflow dispatch or fallback to main
        id: eval_tag
        run: |
          if [ -n "${{ github.event.inputs.tag }}" ]; then
            IMAGE_TAG="${{ github.event.inputs.tag }}"
          elif [ -n "${{ inputs.tag }}" ]; then
            IMAGE_TAG="${{ inputs.tag }}"
          else
            ### if not called from dispatch or call, it must be merging to main
            IMAGE_TAG="main"
          fi
          echo "### Using image tag: $IMAGE_TAG"
          echo "tag=${IMAGE_TAG}" >> $GITHUB_OUTPUT

  build-devcontainer:
    runs-on: ubuntu-latest
    needs: get_tag
    steps:
      - name: adding github workspace as safe directory
        run: git config --global --add safe.directory $GITHUB_WORKSPACE

      - uses: actions/checkout@v3

      - id: repository-name-adjusted
        name: Prepare repository name in lower case for docker upload. This supports repository names in mixed case
        uses: ASzc/change-string-case-action@v5
        with:
          string: ${{ github.repository }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Build and push docker image
        uses: docker/build-push-action@v4
        with:
          pull: true
          push: true
          file: ./tools/Dockerfile
          context: .
          build-args: version=latest, USER_ID=0, GROUP_ID=0
          platforms: linux/amd64, linux/arm64
          secrets: |
            "github_token=user:${{ secrets.GITHUB_TOKEN }}"
          tags: ghcr.io/${{ steps.repository-name-adjusted.outputs.lowercase }}/oci_kuksa-val-services-ci:${{ needs.get_tag.outputs.tag }}
          labels: |
            org.opencontainers.image.source=ghcr.io/${{ steps.repository-name-adjusted.outputs.lowercase }}
