# /********************************************************************************
# * Copyright (c) 2022 Contributors to the Eclipse Foundation
# *
# * See the NOTICE file(s) distributed with this work for additional
# * information regarding copyright ownership.
# *
# * This program and the accompanying materials are made available under the
# * terms of the Apache License 2.0 which is available at
# * http://www.apache.org/licenses/LICENSE-2.0
# *
# * SPDX-License-Identifier: Apache-2.0
# ********************************************************************************/

name: hvac-service

on:
  pull_request:
    paths:
      - ".github/workflows/hvac_service.yml"
      - "hvac_service/**"
  workflow_call:
  workflow_dispatch:

jobs:
  build-hvac-service-image:
    name: "Build multi-arch image"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Retrieve build binaries
        uses: actions/download-artifact@v3
        with:
          path: ${{github.workspace}}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - id: repository-name-adjusted
        name: Make repository name in lower case for docker upload.
        uses: ASzc/change-string-case-action@v2
        with:
          string: ${{ github.repository }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: "Build image"
        id: image_build
        uses: docker/build-push-action@v2
        with:
          pull: true
          push: false
          outputs: |
            type=oci,dest=./oci_vservice-hvac.tar
          context: ./hvac_service
          file: ./hvac_service/Dockerfile
          platforms: linux/amd64, linux/arm64
          tags: ${{ github.sha }}
          labels: |
            org.opencontainers.image.source=https://github.com/${{steps.repository-name-adjusted.outputs.lowercase}}

      - name: Temporarily save Docker image
        uses: actions/upload-artifact@v3
        with:
          name: oci_vservice-hvac.tar
          path: ${{github.workspace}}/oci_vservice-hvac.tar
          retention-days: 1
