# /********************************************************************************
# * Copyright (c) 2022 Contributors to the Eclipse Foundation
# *
# * See the NOTICE file(s) distributed with this work for additional
# * information regarding copyright ownership.
# *
# * This program and the accompanying materials are made available under the
# * terms of the Apache License 2.0 which is available at
# * http://www.apache.org/licenses/LICENSE-2.0
# *
# * SPDX-License-Identifier: Apache-2.0
# ********************************************************************************/

name: mock-service

on:
  pull_request:
    paths:
      - ".github/workflows/mock_service.yml"
      - "mock_service/**"
  workflow_call:
  workflow_dispatch:

jobs:
  build-mock-service-image:
    name: Build multi-arch image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Retrieve build binaries
        uses: actions/download-artifact@v3
        with:
          path: ${{github.workspace}}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - id: repository-name-adjusted
        name: Make repository name in lower case for docker upload.
        uses: ASzc/change-string-case-action@v5
        with:
          string: ${{ github.repository }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: "Build image"
        id: image_build
        uses: docker/build-push-action@v5
        with:
          provenance: false
          pull: true
          push: false
          outputs: |
            type=oci,dest=./oci_vservice-mock.tar
          context: ./mock_service
          file: ./mock_service/Dockerfile
          platforms: linux/amd64, linux/arm64
          tags: ${{ github.sha }}
          labels: |
            org.opencontainers.image.source=https://github.com/${{steps.repository-name-adjusted.outputs.lowercase}}

      - name: Temporarily save Docker image
        uses: actions/upload-artifact@v3
        with:
          name: oci_vservice-mock.tar
          path: ${{github.workspace}}/oci_vservice-mock.tar
          retention-days: 1

  ensure-docs-up2date:
    name: Ensure docs are up2date
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: (Re-) Build Pydoc Markdown
        shell: bash
        working-directory: mock_service
        run: |
          ./update-api-docs.sh

      - name: Has Changes
        id: changes
        run: |
          if [[ -z "$(git status --porcelain .)" ]];
          then
            echo "changed=0" >> $GITHUB_OUTPUT
          else
            echo "changed=1" >> $GITHUB_OUTPUT
          fi
        shell: bash

      - name: Fail if there are changes
        if: steps.changes.outputs.changed == 1
        run: exit 1

  run-tests:
    name: Run tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        shell: bash
        working-directory: mock_service
        run: |
          python3 -m pip install --pre -r ./requirements.txt
          python3 -m pip install -r ./requirements-dev.txt

      - name: Run tests
        shell: bash
        working-directory: mock_service
        run: |
          python3 -m pytest
