# /********************************************************************************
# * Copyright (c) 2022 Contributors to the Eclipse Foundation
# *
# * See the NOTICE file(s) distributed with this work for additional
# * information regarding copyright ownership.
# *
# * This program and the accompanying materials are made available under the
# * terms of the Apache License 2.0 which is available at
# * http://www.apache.org/licenses/LICENSE-2.0
# *
# * SPDX-License-Identifier: Apache-2.0
# ********************************************************************************/

name: seat-service-build

on:
  pull_request:
    paths:
      - ".github/workflows/seat_service_build.yml"
      - "seat_service/**"
      - "vehicle_data_broker/proto/**"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build
    container:
      image: ghcr.io/${{ github.repository }}/oci_kuksa-val-services-ci:prerelease
      credentials:
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}
    strategy:
      matrix:
        target-arch: [x86_64, aarch64]
      fail-fast: true
    env:
      BUILD_TYPE: Debug

    steps:
      - name: adding github workspace as safe directory
        run: git config --global --add safe.directory $GITHUB_WORKSPACE

      - uses: actions/checkout@v3

      - name: Run build
        working-directory: ${{github.workspace}}/seat_service
        run: ./build-debug.sh ${{ matrix.target-arch }}

      - name: Upload binaries
        uses: actions/upload-artifact@v3
        with:
          name: bin_vservice-seat_${{ matrix.target-arch }}_debug
          path: |
            ${{github.workspace}}/seat_service/target/${{ matrix.target-arch }}/debug/install
          if-no-files-found: error

      - name: Test (x86_64)
        if: ${{ matrix.target-arch == 'x86_64' }}
        working-directory: ${{github.workspace}}/seat_service/target/x86_64/debug/
        run: ctest -j -T memcheck -C ${{env.BUILD_TYPE}} --output-on-failure -E '(example)'

      - name: Upload Test results (x86_64)
        if: ${{ matrix.target-arch == 'x86_64' }}
        uses: actions/upload-artifact@v3
        with:
          name: report_test_vservice-seat
          path: |
            ${{github.workspace}}/seat_service/target/x86_64/debug/Testing
          if-no-files-found: error
