# /********************************************************************************
# * Copyright (c) 2022 Contributors to the Eclipse Foundation
# *
# * See the NOTICE file(s) distributed with this work for additional
# * information regarding copyright ownership.
# *
# * This program and the accompanying materials are made available under the
# * terms of the Apache License 2.0 which is available at
# * http://www.apache.org/licenses/LICENSE-2.0
# *
# * SPDX-License-Identifier: Apache-2.0
# ********************************************************************************/

name: seat-service-release

on:
  pull_request:
    paths:
      - ".github/workflows/seat_service_release.yml"
      - "seat_service/**"
      - "kuksa_data_broker/proto/**"
  workflow_dispatch:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build
    container:
      image: ghcr.io/${{ github.repository }}/oci_kuksa-val-services-ci:v0.1.0
      credentials:
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}
    strategy:
      matrix:
        target-arch: [x86_64, aarch64]
      fail-fast: true
    env:
      CONAN_USER_HOME: "${{ github.workspace }}/conan_user_home/"

    steps:
      - name: adding github workspace as safe directory
        run: git config --global --add safe.directory $GITHUB_WORKSPACE

      - uses: actions/checkout@v3

      - name: Using the builtin GitHub Cache Action for .conan
        id: cache-conan
        uses: actions/cache@v3.0.2
        env:
          cache-name: cache-conan-modules
        with:
          path: ${{ env.CONAN_USER_HOME }}
          key: ${{ runner.os }}-builder-${{ matrix.target-arch }}-${{ env.cache-name }}-${{ hashFiles('seat_service/conanfile.txt') }}
          restore-keys: ${{ runner.os }}-builder-${{ matrix.target-arch }}-${{ env.cache-name }}-

      - name: Run build
        working-directory: ${{github.workspace}}/seat_service
        run: ./build-release.sh ${{ matrix.target-arch }}

      - name: Tar files
        shell: bash
        working-directory: ${{github.workspace}}/seat_service/
        run: |
          tar -czvf bin_vservice-seat_${{ matrix.target-arch }}_release.tar.gz \
          target/${{ matrix.target-arch }}/release/install/ \
          target/${{ matrix.target-arch }}/release/licenses/ \
          proto/
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: bin_vservice-seat_${{ matrix.target-arch }}_release.tar.gz
          path: ${{github.workspace}}/seat_service/bin_vservice-seat_${{ matrix.target-arch }}_release.tar.gz
          if-no-files-found: error

  build-seat-service-image:
    name: "Build multi-arch image (seat_service)"
    runs-on: ubuntu-latest
    needs: [build]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Retrieve build binaries
        uses: actions/download-artifact@v3
        with:
          path: ${{github.workspace}}/seat_service

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - id: repository-name-adjusted
        name: Make repository name in lower case for docker upload.
        uses: ASzc/change-string-case-action@v2
        with:
          string: ${{ github.repository }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: "Build seat service image"
        id: image_build
        uses: docker/build-push-action@v2
        with:
          pull: true
          push: false
          outputs: |
            type=oci,dest=./oci_vservice-seat.tar
          context: .
          file: ./seat_service/Dockerfile
          platforms: linux/amd64, linux/arm64
          tags: ${{ github.sha }}
          labels: |
            org.opencontainers.image.source=https://github.com/${{steps.repository-name-adjusted.outputs.lowercase}}

      - name: Temporarily save Docker image
        uses: actions/upload-artifact@v3
        with:
          name: oci_vservice-seat.tar
          path: ${{github.workspace}}/oci_vservice-seat.tar
          retention-days: 1
